### ISSUE TITLE
Determine how to create a data package 

### ISSUE THREAD

**Issue by elachtara** [Amherst-Statistics/ValleyBikes#3]
and where to stuff things so that they are ignored by the data package

**Comment by nicholasjhorton** [comment]
For now let's put things into folders called "resources", "code", and "data-raw".

**Comment by nicholasjhorton** [comment]
See https://github.com/mcconvil/pdxTrees and https://teachdatascience.com/datapackage/ for some examples.

**Comment by nicholasjhorton** [comment]
proposed contents for Fall 2019:
- a week's worth of individual xlsx files
- an Rda file with one interesting bike
- an Rda file with one month's worth of data 2018
- an Rda file with another month's worth of data from 2018
- two more Rda files with the same months in 2019

proposed longer-term:
- also include instructions to download all of the data and put it into a database as per the etl package framework

**Comment by shukryzablah** [comment]
Note that I have deleted the old uploaded data from the repo, but I have all the zipped csvs locally. 
I have not made progress so far with creating the package. Should have more time now that analysis gains momentum.

**Comment by nicholasjhorton** [comment]
Big contribution of @shukryzablah and @elachtara: let's make only the start and end location available (two lines per trip)?  Suddenly the dataset is a lot more manageable.  

In addition, we could include a few days from 2019 of full data to let folks start to explore paths, speeds, etc.  

this will rely on the stationID from the other analyses to identify locations.

**Comment by nicholasjhorton** [comment]
See https://github.com/Amherst-Statistics/CollegeScorecard as a possible model to include a set of full daily datasets to complement the full two lines per trip pruned version that you've created.

**Comment by nicholasjhorton** [comment]
The package is failing checks: 

> devtools::check()
Updating ValleyBikes documentation
Updating roxygen version in /Users/nhorton/Dropbox/git/ValleyBikes/DESCRIPTION
Loading ValleyBikes
Writing ValleyBikes.Rd
── Building ───────────────────────────────────────────────────────────────────────────────────────────────────────── ValleyBikes ──
Setting env vars:
● CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
● CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
● CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/Users/nhorton/Dropbox/git/ValleyBikes/DESCRIPTION’ ...
─  preparing ‘ValleyBikes’: (1s)
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
E  creating vignettes (3.1s)
   --- re-building ‘vbvignette.Rmd’ using rmarkdown
   
   		Information on package 'ValleyBikes'
   
   Description:
   
   Package:           ValleyBikes
   Title:             Valley Bike route and station data.
   Version:           0.0.0.9001
   Authors@R:         person(given = "Shukry", family = "Zablah", role =
                      c("aut", "cre"), email = "szablah20@amherst.edu")
                      person(given = "Emily", family = "Lachtara", role =
                      c("aut", "cre"), email = "elachtara21@amherst.edu")
                      person(given = "Nicholas", family = "Horton", role =
                      c("aut", "cre"), email = "nhorton@amherst.edu")
   Description:       The package provides route and station data from
                      2018-2019 for the Valley Bikes bikeshare system. It
                      also provides an example of the raw GPS data.
   License:           MIT
   Encoding:          UTF-8
   LazyData:          true
   RoxygenNote:       7.0.0
   Suggests:          knitr, rmarkdown
   VignetteBuilder:   knitr
   Author:            Nicholas Horton [aut, cre]
   Maintainer:        Nicholas Horton <nhorton@amherst.edu>
   Built:             R 3.6.1; ; 2019-12-04 19:37:13 UTC; unix
   
   Index:
   
   ValleyBikes             ValleyBikes: A package for exploring data from
                           Pioneer Valley bikeshare.
   routes                  Routes
   stations                Stations
   
   Quitting from lines 47-54 (vbvignette.Rmd) 
   Error: processing vignette 'vbvignette.Rmd' failed with diagnostics:
   could not find function "%>%<-"
   --- failed re-building ‘vbvignette.Rmd’
   
   SUMMARY: processing the following file failed:
     ‘vbvignette.Rmd’
   
   Error: Vignette re-building failed.
   Execution halted
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command error

**Comment by elachtara** [comment]
the error in the vingett is resolved
