### ISSUE TITLE
Generate the table of stations locations

### ISSUE THREAD

**Issue by elachtara** [Amherst-Statistics/ValleyBikes#4]

**Comment by nicholasjhorton** [comment]
This is all the background I have:



On Jul 2, 2019, at 1:20 PM, Yanik Hardy <yanik@bewegen.com> wrote:

Hi Nick,

Maybe you can start with this?  https://www.valleybike.org/  Click on any icon and you will have station info i.e. name, address, number of docks.

We don't have an actual file like you're looking for.

Yanik

-----Message d'origine-----
De : Nicholas Horton <nicholasjhorton@gmail.com> 
Envoyé : 30 juin 2019 15:44
À : Yanik Hardy <yanik@bewegen.com>
Cc : Nicholas Horton <nicholasjhorton@gmail.com>; Wayne Feiden <wfeiden@northamptonma.gov>
Objet : query about dock locations

Yanik,

Do you have a file which maps dock locations to dock names?  I know many of them but not all.

Thanks in advance for any guidance,

Nick

**Comment by elachtara** [comment]
would it be best if I do this in excel file?

**Comment by nicholasjhorton** [comment]
My suggestion would be to use one day's worth of data from 2019 (not yet available, substitute 2018 for now) and generate the set of all starting locations and ending locations.  Those lat/long combinations should be the stations.  I'd prefer to do this using an R Markdown file.

**Comment by elachtara** [comment]
me and shukry have made progress on this and are trying to read in multiple days in order to get all the stations.

**Comment by nicholasjhorton** [comment]
Can you please add a link to the code on github?

**Comment by shukryzablah** [comment]
The [code](https://github.com/Amherst-Statistics/ValleyBikes/blob/master/exploratory/update1.Rmd) is in the update#1 file. 

Next step is checking if we can join a table (with names for stations) from a report in the government file cabinet, and our generated stations table.

**Comment by shukryzablah** [comment]
We will use the json that is requested by the valleybike.org site to get the table of stations.

We got the following link by inspecting the network requests made by the site: 

https://valleybike.org/stations/stations/

**Comment by nicholasjhorton** [comment]
Nice!

**Comment by elachtara** [comment]
Check out the file "StationLocationScraping"

**Comment by nicholasjhorton** [comment]
This is shaping up well.  Can you please add an example for how to plot the station locations to the ValleyBikes package github repo?

**Comment by nicholasjhorton** [comment]
I'm hoping that we can review the workflow here for the data package.  But I'm not seeing the file StationLocationScraping in the current repo.  Can you please advise?

**Comment by shukryzablah** [comment]
Check out this file: https://github.com/Amherst-Statistics/ValleyBikes/blob/master/code/stations.Rmd or it's [pdf](https://github.com/Amherst-Statistics/ValleyBikes/blob/master/reports/stations.pdf)

**Comment by nicholasjhorton** [comment]
That looks great and is helpful.  

But I was more curious about the workflow to generate the stations, as we will need to run it in the future.  Can you please send a pointer to that when you have a chance?

**Comment by shukryzablah** [comment]
The data-raw folder contains scripts to recreate the data objects that will be included in the package. Check out this file:  https://github.com/Amherst-Statistics/ValleyBikes/blob/master/data-raw/stations.R

**Comment by nicholasjhorton** [comment]
Cool.  So am I correct in understanding that the Station locations are now coming from the ValleyBikes website (and not being generated using the paths of the bikes?

**Comment by shukryzablah** [comment]
Yes. There is the small addition of the clustering into communities since
that was not included originally and felt useful.
