### ISSUE TITLE
convert analyses into vignettes

### ISSUE THREAD

**Issue by nicholasjhorton** [Amherst-Statistics/ValleyBikes#5]
Does that sound workable?  Can you please share a draft of your Rmd file?

**Comment by elachtara** [comment]
Yes, I will generate some ideas for questions and post them and then we can get going on the code. Do we have any idea as to what questions Wayne and crew want answered?

**Comment by nicholasjhorton** [comment]
One question I'm interested in: how does usage vary in Amherst during the school year vs. during the summer?  We can probably best compare August weekends and weekdays to September weekends and weekdays in 2018.

**Comment by shukryzablah** [comment]
The [first update](https://github.com/Amherst-Statistics/ValleyBikes/blob/master/reports/update1.pdf) has initial work. 

After identifying the lat/lon boundaries of Amherst we will tackle that question and go from there.

**Comment by elachtara** [comment]
Question: this meeting is with the other fellows or Wayne?

**Comment by nicholasjhorton** [comment]
The other fellows.  But I'm hoping to start to share a plan updates with Wayne when I see him tomorrow.

**Comment by nicholasjhorton** [comment]
This is off to a good start.  But I worry that you've miscoded hour of day.  Are these perchance GMT or European time?  The figure looks much more plausible with such a shift.

Can you please add a revised pdf to github?  I've added a folder https://github.com/Amherst-Statistics/StatFellows/tree/master/meeting2019-10-21

**Comment by nicholasjhorton** [comment]
I've retrieved older files from the previous master copy of the repo (see https://github.com/Amherst-Statistics/ValleyBikes/tree/master/old-to-review).  Will these help with the analyses?

**Comment by nicholasjhorton** [comment]
@elachtara any updates on the old files?  It would be very helpful to start to transition these into vignettes for the data package.

**Comment by elachtara** [comment]
mapping trip, most popular locations/stations.

**Comment by elachtara** [comment]
make sure package works ok for vignette

**Comment by elachtara** [comment]
package install check ? can you install it reliably

**Comment by nicholasjhorton** [comment]
Here's a pointer to more information on package installation checking: http://r-pkgs.had.co.nz/check.html
