### ISSUE TITLE
Getting distances for each community

### ISSUE THREAD

**Issue by shukryzablah** [Amherst-Statistics/ValleyBikes#9]
[Check out the pdf.](https://github.com/Amherst-Statistics/ValleyBikes/blob/master/reports/distance2.pdf)

No sampling being done so this approach is inefficient right now (left running over night). Slimming down results to have only 100 or 300 (equally spaced in time) points per route, had similar results. Any value we pick that slims down the data will underestimate the actual distance. Right now we find a total of 147458 mi (actual one in website is185790.84mi) for current year. 

The proportions stayed similar when picking 100 points per route and 300 points per route. 

The basic idea is for each day 1) slim down to N points per route, 2) find community for N entries of any given route, 3) aggregate per route per community the distances given by N entries. In the end we aggregate by community to get the final results.

**Comment by nicholasjhorton** [comment]
I like how this is shaping up.  Your underestimation to yield proportions may be exactly what Wayne Feiden is after.  

What's next on your end before I share the results?  @elachtara do you have any thoughts or questions?

**Comment by shukryzablah** [comment]
I don't think I can do further work before Wayne's meeting. 

I did want to give you a sense of how the underestimation behaves: 

```
Number of points to select per route |   Total Distance in 2019 (compared to 185790.84mi)
                           5          |                     89950
                           10        |                    109971
                           100      |                    141464
                           300      |                    147458
```

Emily and I will meet Friday and see how we can make use of our work with getting distances as we move forward with the package.

**Comment by nicholasjhorton** [comment]
I'm pleased to report that I shared the estimates with Wayne (I converted them to proportions) and he was excited by the results.  Kudos for pulling this together in such a clear and helpful way!
